videoCapture:
  capture: file

  file:
    src: assets/videos/cars_driving.mp4

  camera:
    src: 0
    fourcc: MJPG
    resolution: [640, 480]
    fps: 30

  piCamera:
    src: 0
    resolution: [640, 480]
    framerate: 30
    settings:
      rotation: 180

  stream:
    # Jetson Nano camera stream
    src: >-
      nvarguscamerasrc sensor-id=0 sensor_mode=3 !
      video/x-raw(memory:NVMM), width=(int)1280, height=(int)720, format=(string)NV12, framerate=(fraction)30/1 !
      nvvidconv flip-method=2 !
      video/x-raw, width=(int)640, height=(int)480, format=(string)BGRx !
      videoconvert !
      video/x-raw, format=(string)BGR !
      appsink
    api_preference: CAP_GSTREAMER