# Video capturing settings
videoCapture:
  capture: file

  file:
    src: assets/videos/people_walking.mp4
    # You can select the frame range for a video file
    # start_frame: 1
    # end_frame: 500

  # For src as a camera index you can check the camera capabilities running:
  #   v4l2-ctl --list-formats-ext -d /dev/video{src}
  # To list all devices:
  #   v4l2-ctl --list-devices
  # If the command v4l2-ctl is not available in your system run:
  #   sudo apt-get install v4l-utils
  camera:
    src: 0
    fourcc: MJPG
    #fourcc: YUYV
    resolution: [640, 480]
    fps: 30

  piCamera:
    src: 0
    resolution: [640, 480]
    framerate: 30
    settings:
      rotation: 180

  stream:
    # GStream test stream
    #src: videotestsrc ! appsink

    # Jetson Nano camera stream
    src: >-
      nvarguscamerasrc sensor-id=0 sensor_mode=3 !
      video/x-raw(memory:NVMM), width=(int)1280, height=(int)720, format=(string)NV12, framerate=(fraction)30/1 !
      nvvidconv flip-method=2 !
      video/x-raw, width=(int)640, height=(int)480, format=(string)BGRx !
      videoconvert !
      video/x-raw, format=(string)BGR !
      appsink
    api_preference: CAP_GSTREAMER

  # Transform video frames
  transform:
    resize:
      width: 320
    # 1 - for removing mirror effect
    flip: 1  # 0 - vertical, 1 - horizontal, -1 - vertical and horizontal